# Generated by Django 4.2.7 on 2024-01-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatflix', '0002_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
