# Generated by Django 4.2.7 on 2024-01-29 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eatflix', '0003_alter_sub_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sub',
        ),
    ]
