# Generated by Django 4.2.7 on 2024-01-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatflix', '0005_alter_subscription_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='date',
            field=models.CharField(choices=[('1 Month', '1 Month'), ('2 Months', '2 Months'), ('3 Months', '3 Months'), ('4 Months', '4 Months'), ('5 Months', '5 Months'), ('6 Months', '6 Months'), ('7 Months', '7 Months'), ('8 Months', '8 Months'), ('9 Months', '9 Months'), ('10 Months', '10 Months'), ('11 Months', '11 Months'), ('1 Year', '1 Year')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='phone',
            field=models.IntegerField(blank=True, max_length=50),
        ),
    ]
