# Generated by Django 5.0 on 2024-02-01 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eatflix', '0007_subscription_id_alter_subscription_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='ID',
            new_name='eatflix_id',
        ),
    ]
