# Generated by Django 5.0 on 2024-02-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatflix', '0010_rename_food_date_added_food_date_added_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('femail', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
