# Generated by Django 5.0 on 2024-02-01 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eatflix', '0011_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='feeds',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='femail',
            new_name='femails',
        ),
    ]
