# Generated by Django 5.0 on 2024-02-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatflix', '0014_rename_sub_id_subscription_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcriptionDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_subscription', models.DateTimeField(auto_now=True)),
                ('date', models.CharField(choices=[('1 Month', '1 Month'), ('2 Months', '2 Months'), ('3 Months', '3 Months'), ('4 Months', '4 Months'), ('5 Months', '5 Months'), ('6 Months', '6 Months'), ('7 Months', '7 Months'), ('8 Months', '8 Months'), ('9 Months', '9 Months'), ('10 Months', '10 Months'), ('11 Months', '11 Months'), ('1 Year', '1 Year')], default='1', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='date_subscription',
        ),
    ]
