# Generated by Django 5.0 on 2024-02-01 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatflix', '0015_subcriptiondate_remove_subscription_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='sub_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eatflix.subcriptiondate'),
        ),
    ]
