# Generated by Django 5.0 on 2024-02-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatflix', '0016_subscription_sub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcriptiondate',
            old_name='date',
            new_name='sub_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='sub_date',
        ),
        migrations.AddField(
            model_name='subscription',
            name='sub_date',
            field=models.ManyToManyField(related_name='SubcriptionDate', to='eatflix.subcriptiondate'),
        ),
    ]
