# Generated by Django 5.0 on 2024-02-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatflix', '0017_rename_date_subcriptiondate_sub_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubcriptionDate',
            new_name='SubscriptionDate',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_date',
            field=models.ManyToManyField(related_name='SubscriptionDate', to='eatflix.subcriptiondate'),
        ),
    ]
