# Generated by Django 5.0 on 2024-02-01 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatflix', '0018_rename_subcriptiondate_subscriptiondate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='sub_date',
        ),
        migrations.AddField(
            model_name='subscription',
            name='sub_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SubscriptionDate', to='eatflix.subscriptiondate'),
        ),
    ]
