# Generated by Django 5.0 on 2024-02-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatflix', '0020_rename_sub_date_subscriptiondate_subs_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='sub_date',
        ),
        migrations.AddField(
            model_name='subscription',
            name='date',
            field=models.CharField(choices=[('1 Month', '1 Month'), ('2 Months', '2 Months'), ('3 Months', '3 Months'), ('4 Months', '4 Months'), ('5 Months', '5 Months'), ('6 Months', '6 Months'), ('7 Months', '7 Months'), ('8 Months', '8 Months'), ('9 Months', '9 Months'), ('10 Months', '10 Months'), ('11 Months', '11 Months'), ('1 Year', '1 Year')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='date_subscription',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='SubscriptionDate',
        ),
    ]
